version: '3.8'

services:
  # --- BACKEND LAYER ---
  db:
    build: ./02-images/dockerfiles/postgres
    container_name: lab-postgres
    networks:
      - net-back
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

  cache:
    build: ./02-images/dockerfiles/redis
    container_name: lab-redis
    networks:
      - net-back

  # --- ADMIN LAYER ---
  adminer:
    build: ./02-images/dockerfiles/adminer
    container_name: lab-adminer
    ports:
      - "8080:8080"
    networks:
      - net-back
      - net-admin

  # --- MONITORING LAYER ---
  prometheus:
    build: ./02-images/dockerfiles/prometheus
    container_name: lab-prometheus
    networks:
      - net-monitor
      - net-back # Pour monitorer la DB plus tard
    volumes:
      - prometheus_data:/prometheus

  grafana:
    build: ./02-images/dockerfiles/grafana
    container_name: lab-grafana
    ports:
      - "3000:3000"
    networks:
      - net-monitor

  cadvisor:
    build: ./02-images/dockerfiles/cadvisor
    container_name: lab-cadvisor
    networks:
      - net-monitor
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro

networks:
  net-back:
    driver: bridge
    internal: true # Empêche l'accès direct depuis l'extérieur
  net-admin:
    driver: bridge
  net-monitor:
    driver: bridge

volumes:
  postgres_data:
  prometheus_data: